version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: teambuilder-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teambuilder
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
