version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: teambuilder-db
    environment:
      POSTGRES_USER: Ut09Q10h6kHqe9tMCstkdRzAajW
      POSTGRES_PASSWORD: tOKyl6zx8HXsPpDbkVXPrJn5x7
      POSTGRES_DB: teambuilder
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
